---
schema:
  procedures: {}
  tables:
    host:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 50
        password:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 4
          size:
            - 64
        port:
          data_type: integer
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: port
          order: 3
          size:
            - 0
      indices: []
      name: host
      options: []
      order: 1
    statval:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - host
          match_type: ''
          name: statval_fk_host
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: host
          type: FOREIGN KEY
      fields:
        datetime:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: datetime
          order: 2
          size:
            - 0
        decimal:
          data_type: decimal
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: decimal
          order: 6
          size:
            - 10
            - 2
        host:
          data_type: integer
          default_value: 0
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: host
          order: 4
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        param:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: param
          order: 7
          size:
            - 50
        plugin:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: plugin
          order: 5
          size:
            - 50
        stattype:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: stattype
          order: 3
          size:
            - 50
      indices:
        - fields:
            - host
          name: statval_idx_host
          options: []
          type: NORMAL
      name: statval
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Host
      - Statval
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
